# -*- coding: utf-8 -*-
"""
Маппинг стран на валюты для проверки доступности через API.
Пользователь вводит страну — бот определяет валюту и проверяет её в api.exchangerate.host/list.
"""

# Названия стран (рус/англ и варианты) -> трёхбуквенный код валюты
COUNTRY_TO_CURRENCY = {
    "россия": "RUB",
    "russia": "RUB",
    "рф": "RUB",
    "китай": "CNY",
    "china": "CNY",
    "турция": "TRY",
    "turkey": "TRY",
    "таиланд": "THB",
    "thailand": "THB",
    "япония": "JPY",
    "japan": "JPY",
    "германия": "EUR",
    "germany": "EUR",
    "франция": "EUR",
    "france": "EUR",
    "италия": "EUR",
    "italy": "EUR",
    "испания": "EUR",
    "spain": "EUR",
    "польша": "PLN",
    "poland": "PLN",
    "чехия": "CZK",
    "czech": "CZK",
    "великобритания": "GBP",
    "great britain": "GBP",
    "англия": "GBP",
    "uk": "GBP",
    "gb": "GBP",
    "сша": "USD",
    "usa": "USD",
    "америка": "USD",
    "us": "USD",
    "usa": "USD",
    "украина": "UAH",
    "ukraine": "UAH",
    "казахстан": "KZT",
    "kazakhstan": "KZT",
    "беларусь": "BYN",
    "belarus": "BYN",
    "вьетнам": "VND",
    "vietnam": "VND",
    "индия": "INR",
    "india": "INR",
    "индонезия": "IDR",
    "indonesia": "IDR",
    "оаэ": "AED",
    "uae": "AED",
    "дубай": "AED",
    "dubai": "AED",
    "египет": "EGP",
    "egypt": "EGP",
    "грузия": "GEL",
    "georgia": "GEL",
    "армения": "AMD",
    "armenia": "AMD",
    "азербайджан": "AZN",
    "azerbaijan": "AZN",
    "швейцария": "CHF",
    "switzerland": "CHF",
    "австралия": "AUD",
    "australia": "AUD",
    "канада": "CAD",
    "canada": "CAD",
    "бразилия": "BRL",
    "brazil": "BRL",
    "мексика": "MXN",
    "mexico": "MXN",
    "южная корея": "KRW",
    "south korea": "KRW",
    "корея": "KRW",
    "korea": "KRW",
    "сингапур": "SGD",
    "singapore": "SGD",
    "малайзия": "MYR",
    "malaysia": "MYR",
    "филиппины": "PHP",
    "philippines": "PHP",
    "израиль": "ILS",
    "israel": "ILS",
    "юар": "ZAR",
    "south africa": "ZAR",
    "аргентина": "ARS",
    "argentina": "ARS",
    "чили": "CLP",
    "chile": "CLP",
    "колумбия": "COP",
    "colombia": "COP",
    "перу": "PEN",
    "peru": "PEN",
    "гонконг": "HKD",
    "hong kong": "HKD",
    "тайвань": "TWD",
    "taiwan": "TWD",
    "новая зеландия": "NZD",
    "new zealand": "NZD",
    "норвегия": "NOK",
    "norway": "NOK",
    "швеция": "SEK",
    "sweden": "SEK",
    "дания": "DKK",
    "denmark": "DKK",
    "исландия": "ISK",
    "iceland": "ISK",
    "венгрия": "HUF",
    "hungary": "HUF",
    "румыния": "RON",
    "romania": "RON",
    "болгария": "BGN",
    "bulgaria": "BGN",
    "хорватия": "HRK",
    "croatia": "HRK",
    "сербия": "RSD",
    "serbia": "RSD",
    "греция": "EUR",
    "greece": "EUR",
    "португалия": "EUR",
    "portugal": "EUR",
    "нидерланды": "EUR",
    "netherlands": "EUR",
    "бельгия": "EUR",
    "belgium": "EUR",
    "австрия": "EUR",
    "austria": "EUR",
    "ирландия": "EUR",
    "ireland": "EUR",
    "финляндия": "EUR",
    "finland": "EUR",
    "словения": "EUR",
    "slovenia": "EUR",
    "словакия": "EUR",
    "slovakia": "EUR",
    "эстония": "EUR",
    "estonia": "EUR",
    "латвия": "EUR",
    "latvia": "EUR",
    "литва": "EUR",
    "lithuania": "EUR",
    "мальта": "EUR",
    "malta": "EUR",
    "кипр": "EUR",
    "cyprus": "EUR",
}


def country_to_currency(country_input: str):
    """
    Возвращает код валюты по названию страны или None.
    Если ввод уже похож на код валюты (3 латинские буквы), возвращает его в верхнем регистре.
    """
    if not country_input or not isinstance(country_input, str):
        return None
    s = country_input.strip().lower()
    if len(s) == 3 and s.isalpha():
        return s.upper()
    return COUNTRY_TO_CURRENCY.get(s)
